# Generated by Django 4.2.6 on 2023-11-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('standard', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
