# Generated by Django 4.2.6 on 2023-11-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0002_students_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
